### ISSUE TITLE
Publishing UX Cleanup

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-app#373] opened 2017-07-21 17:36 UTC
There are a few outstanding small UX issues:

- Placeholder values are confusing
- The difference between channels and URLs is confusing, as is the term "Identity"
- The field order should be reconsidered

## The Issue
Users mistake this tool tip/gray text as a requirement.
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Either make it totally blank and add an extended "How much is enough?" style tool-tip link, make it even lighter gray text for the "10," or maybe "XX LBC" is better?

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment] 2017-11-20 20:24
Closing since duplicate of https://github.com/lbryio/lbry-app/issues/540

**Closed by seanyesmunt** 2017-11-20 20:24 UTC
Labels: UX
