### ISSUE TITLE
Bring back Open File Location / way to locate downloaded file

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#606] opened 2017-09-22 14:36 UTC
## The Issue
In v16, users lost the ability to open the file explorer to the location of the file. Right now they can open the file manually using Open (which opens it externally) or they can see the path in the "Downloaded to" section.  So currently its difficult to locate the file because you don't even know what its called. 

Maybe the solution is to add the filename to the "Downloaded to" path (need to worry about wrapping) but make it open to the file as opposed to opening the file itself? Or add another field with the filename which opens to the path? 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment] 2017-09-22 21:01
If the link for "Downloaded To" is not opening the folder when clicked, this is a bug.

If it _is_ doing that, but you were confused, then this is just poor design.

**Comment by tzarebczan** [comment] 2017-09-22 21:06
It opens to the folder which contains the LBRY download folder. I.e. my downloads folder is "D:\LBRY Downloads" and clicking the link goes to D:\ and highlights the LBRY Downloads folder.  Not sure if that was the intention or not. The scenario I was talking about is where it highlights the particular downloaded file inside the downloads folder.

**Comment by kauffj** [comment] 2017-09-22 21:11
This is a bug, since it is supposed to open the folder. But I think it is a UX issue too, since the intended behavior was unclear.

**Comment by btzr-io** [comment] 2017-09-23 18:26
Fixed but won't work in linux:
https://github.com/electron/electron/blob/db6d75ca90ebe23d70f40f767264f7c2d77f882e/atom/common/platform_util_linux.cc#L70

**Comment by btzr-io** [comment] 2017-09-23 18:56
Linux needs a fallback:
Ubuntu: `nautilus /path/myFile.txt`
Elementary: `pantheon-files /path/myFile.txt`

**Comment by btzr-io** [comment] 2017-09-23 22:49
Need some confirmation / feedback to send a PR :stuck_out_tongue:

**Comment by btzr-io** [comment] 2017-09-24 02:46
This needs to be merged first: https://github.com/lbryio/lbry-app/pull/61

**Closed** 2017-09-24 20:37 UTC
Labels: bug, enhancement, UX
