### ISSUE TITLE
lbry:// URL fails to open if app is closed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#190] opened 2017-06-02 20:28 UTC
## The Issue
Clicking on lbry://lbry-intro from a browser while the LBRY app is closed does not lead to the app opening the desired URL. Instead, you get the discover page
### Steps to reproduce
1. Ensure LBRY app is closed
2. Open lbry://lbry-intro
3. Discover page shown

### Expected behaviour
should go to lbry://lbry-intro

### Actual behaviour
app opens, discover page shown

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 0.11.9
- LBRY Installation ID:
- Operating system: Windows

**Comment by alexliebowitz** [comment] 2017-06-03 07:43
Reproduced on Windows but not Mac. Clearly the app knows what it's supposed to be opening (you see the URI in the title bar). So it seems to be at the UI layer, which makes it weird that it's only happening on Windows. I'll figure it out. Thanks.

**Comment by tzarebczan** [comment] 2017-06-03 16:20
@alexliebowitz I can open another issue, but on Linux I'm getting different behavior when clicking on a hyperlink. A 2nd instance of the lbry app opens the URI instead of the existing app/window. Is this intended behavior on Linux?

**Comment by alexliebowitz** [comment] 2017-06-06 07:19
@tzarebczan: That is known and comes down to a problem with Electron. See #164. We may have to work around it.

**Comment by tzarebczan** [comment] 2017-06-12 20:42
@alexliebowitz any updates? Still around on latest build.

**Comment by kauffj** [comment] 2017-06-30 20:31
This should be fixed in 0.13.

**Closed by kauffj** 2017-06-30 20:31 UTC

**Comment by tzarebczan** [comment] 2017-06-30 22:09
Confirmed fixed!
