### ISSUE TITLE
Two Children with Same Key While Publishing

### ISSUE THREAD

**Issue by 98farhan94** [lbryio/lbry-app#342] opened 2017-07-09 21:44 UTC
## The Issue
Children having same key, possible conflict.

### Steps to reproduce
1. Go to Publish, open up the dev.
2. Upload and publish the file.
3. Error shows up.

### Expected behaviour
No JS errors.

### Actual behaviour
Two children with same key error.

## System Configuration

 

  "build": "release",
    "lbrynet_version": "0.13.1",
    "lbryschema_version": "0.0.7",
    "lbryum_version": "2.8.4",
    "os_release": "16.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"

## Screenshots

<img width="503" alt="screen shot 2017-07-10 at 2 41 47 am" src="https://user-images.githubusercontent.com/5463117/27997821-e068d5a2-651d-11e7-984e-31ea612c27b3.png">

**Comment by tzarebczan** [comment] 2017-07-09 21:50
Duplicate of https://github.com/lbryio/lbry-app/issues/313. Closing.

**Closed by tzarebczan** 2017-07-09 21:50 UTC
