### ISSUE TITLE
gnome-keyring as a dependency on KDE systems

### ISSUE THREAD

**Issue by filipnyquist** [lbryio/lbry-app#422] opened 2017-08-02 10:31 UTC
Trying to run the app on KDE systems fails because of is requireing the gnome-keyring.

it shouldn't be necessary to have the need of using gnome-keyring on KDE systems with a functional KWallet.
I know that org.freedesktop.secrets is not provided by KWallet - yet, so either we can force gnome-keyring as a dependency on KDE systems or find a way to use KWallet through DBus.

Problem arises on KDE systems with the latest verification release, for more info ping me in slack as i'm on phone.

**Comment by tzarebczan** [comment] 2017-08-02 12:14
Similar to https://github.com/lbryio/lbry-app/issues/386

**Comment by lyoshenka** [comment] 2017-09-18 13:15
Duplicate of #386

**Closed by lyoshenka** 2017-09-18 13:15 UTC
