### ISSUE TITLE
[Bug] After upload a video and stay in the "Published" tab, it don't gets updated

### ISSUE THREAD

**Issue by Plasmmer** [lbryio/lbry-app#87] opened 2017-04-27 06:03 UTC

**Comment by alexliebowitz** [comment] 2017-05-04 09:08
Did it ever finally update (or disappear from the file manager)? If so, did it require a refresh or restarting the app?

**Comment by kauffj** [comment] 2017-06-15 23:20
Duplicate of #227 and fixed in pull request.

**Closed by kauffj** 2017-06-15 23:20 UTC

**Comment by Plasmmer** [comment] 2017-06-16 02:55
Not. #227 is a duplicate because my issue is the #87, logically it started first, despite #227 is more detailed.
