### ISSUE TITLE
When trying to claim an existing name, user is not informed of amount needed to win

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-app#214] opened 2017-06-08 22:11 UTC
## The Issue
When publishing content to a claim that has previously been claimed, the application used to display a minimum amount of credits to bid in order to take over the claim.

Now the application will not produce any feedback to inform the client of any other claims, nor will it inform about the amount of credits needed to overtake the claim.

The application will let the publication go through even with smaller non-winning bids. The claim will never come up as winning claim unless all the other top claims will be abandoned.

### Steps to reproduce
1. open the publish tab
2. in the address field fill with an existing name (ie. five)
3. nothing comes up as feedback
4. fill the other fields and publish for a small amount of LBC (ie. 0.1)

### Expected behaviour
the app should enforce a higher bid for the claim or otherwise inform the client.

### Actual behaviour
the application will let everything go through

## System Configuration

```
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "rc",
    "ip": "***********",
    "lbrynet_version": "0.11.0rc1",
    "lbryschema_version": "0.0.6",
    "lbryum_version": "2.7.24",
    "os_release": "4.4.0-78-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-78-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
  }
}
```

## Anything Else
while watching the network through the developer console I couldn't see calls to the daemon to resolve the claim. This might be related to another issue I found.

## Screenshots
unpublished claim: https://scrn.storni.info/2017-06-08_14-11-02-915571679.png

existing claim: https://scrn.storni.info/2017-06-08_14-11-14-451261757.png

the claim publishes even with a smaller bid: https://scrn.storni.info/2017-06-08_14-11-49-512236877.png

**Comment by tzarebczan** [comment] 2017-06-08 22:30
What happens to the file when it's published? I've noticed in past versions that it shows the orignal content (not yours) in published.

**Comment by nikooo777** [comment] 2017-06-08 22:31
The file remains published as if it was an overtaken claim. if for whatever reason the top claim would be abandoned, then this new one would show up

**Comment by kauffj** [comment] 2017-06-09 00:27
@alexliebowitz broken by redux?

**Comment by 6ea86b96** [comment] 2017-06-09 11:33
This seems to be a regression introduced here: https://github.com/lbryio/lbry-app/commit/fc652e221a1ce64ab12ad0a318c5b67e8f64a503.

The claim data here `lbry.resolve({uri: name}).then((claimInfo) => ` is inside of `claimInfo.claim`.

**Comment by tzarebczan** [comment] 2017-06-09 22:50
@kauffj / @alexliebowitz still an issue in RC7, don't think it was addressed.  ?

**Comment by kauffj** [comment] 2017-06-30 20:27
@6ea86b96 is this on your radar for the `publishing` branch?

**Comment by kauffj** [comment] 2017-07-11 13:11
I believe this is fixed in pull request, will confirm.

**Comment by 6ea86b96** [comment] 2017-07-11 13:26
I'm pretty sure this was working at one point but seems to be broken in the current PR. Will look into fixing it.

**Comment by 6ea86b96** [comment] 2017-07-17 07:13
@kauffj in master now the publish button is disabled until the bid is high enough. They can see the amount that needs to be bid too. Maybe still a bit confusing for some users.

**Comment by kauffj** [comment] 2017-07-18 18:11
@6ea86b96 actually we should allow claims that aren't winning, we should just be clear about it. This is my fault for not correcting the original ticket.

**Comment by 6ea86b96** [comment] 2017-07-19 08:49
ah, ok, I'll take another pass at this then.

**Comment by tzarebczan** [comment] 2017-07-25 21:32
In the latest version, the bid amount is shown, but it doesn't take into account the supporting claims. Effective amount should be shown instead. 

@kauffj @6ea86b96

**Comment by tzarebczan** [comment] 2017-07-26 21:19
Also, consider this example when using identities...

When we publish using an identity, we get both lbry://@identity/claim and lbry://claim

When going into the publish screen, the identity is now appended to the URL and shows that bry://@identity/claim is available, which it is, but lbry://claim may not be (has higher bid, etc).  Do we want to handle that somehow, or assume that because someone is using the identity, they don't want the straight vanity URL? Seems like a bad assumption to make as I can see why someone would want lbry://one and put the claim under their identity.

**Comment by tzarebczan** [comment] 2017-07-27 17:06
Also, I think we should show them approximately when their takeover will go into effect, similar to how the content bot in #conent does (assuming it is accurate, but I have doubts):

lbry://nine
Particl.io – Easy, Secure and Private P2P Marketplace Introduction
Visit [https://particl.io](https://particl.io) for more information.
Takes effect on approx. *July 29th at 06:04 UTC* (block 214631)
Block 212574 • Claim ID addd06aab5d05bf3dec12bb2e68416e649af5758

**Comment by tzarebczan** [comment] 2017-08-15 20:45
Another aspect to possibly take into consideration is applying the same type of notification to the channel bidding process as it is also possible to take over vanity channel names.

**Comment by tzarebczan** [comment] 2017-08-28 12:52
@6ea86b96 do you plan to get back to this? If so, we should discuss the above scenarios with @kauffj

**Comment by tzarebczan** [comment] 2017-10-02 13:08
Closing this, I broke out the remaining issues as referenced here.

**Closed by tzarebczan** 2017-10-02 13:08 UTC
Labels: bug, P2
