### ISSUE TITLE
Using Developer->Reload after opening a video results in a blank, stuck window

### ISSUE THREAD

**Issue by avashlin** [lbryio/lbry-app#265] opened 2017-06-20 15:04 UTC
## The Issue
Opening LBRY and then proceeding to attempt to play a video (currently unavailable content). After this, I just selected Developer->Reload on the menu and was faced with a 'green screen of death'. See screenshot below.

### Steps to reproduce
1. Open LBRY
2. Choose a video
3. Wait for it to say content unavailable
4. Select Developer -> Reload from menu
5. observe screenshot for result (blank green screen)

### Expected behaviour
Tell us what should happen
The reload should refresh the interface and essentially reinitialize the processes used.

### Actual behaviour
Tell us what happens instead
Blank green screen shown with no content or interface to interact with

## System Configuration

 
![screenshot from 2017-06-20 15-26-07](https://user-images.githubusercontent.com/8122968/27340056-c48af53e-55d9-11e7-938d-2128e4ccd216.png)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

![screenshot from 2017-06-20 16-58-50](https://user-images.githubusercontent.com/8122968/27340060-c994b394-55d9-11e7-81ee-c96709f42edd.png)

**Comment by kauffj** [comment] 2017-06-20 18:15
Duplicate of #233

**Closed by kauffj** 2017-06-20 18:15 UTC
