### ISSUE TITLE
Video wont open, thumbnail self-destructs 

### ISSUE THREAD

**Issue by CjMapope** [lbryio/lbry-app#184] opened 2017-06-01 22:52 UTC
### Steps to reproduce
1. Navigate to  lbry://three-2
2. HIt play button on thunmbnail
3. Error is apparent, does not play

### Expected behaviour
Should play as per other vids when you click the large play button on the video

### Actual behaviour
Does not play 

## System Configuration

daemon (lbrynet)	0.10.3
wallet (lbryum)	2.7.22
interface	0.11.9
Platform	Windows (Windows-10-10.0.14393)
Installation ID	6PhVeRWUZfr9UtTPrkcKnLVv4qBakiuzvfDhSqwPAGZTeBfXfi3EHbnhuFnVheugyc

## Anything Else
Also seems to remove the play button after from center of video, even tho it did NOT play
## Screenshots

![issue](https://cloud.githubusercontent.com/assets/12862793/26704158/842823a2-46ea-11e7-96b8-73c23d52012f.PNG)

**Comment by tzarebczan** [comment] 2017-06-01 23:01
It is a mov file, which might be why it's acting this way.

**Comment by 6ea86b96** [comment] 2017-06-08 13:25
This is definitely the cause. LBRY uses a HTML5 `video` tag under the hood, which does not support this file for

**Comment by kauffj** [comment] 2017-06-30 20:34
This will be fixed in 0.13.1 (in the sense that it will prompt to download)

**Closed by kauffj** 2017-06-30 20:34 UTC
