### ISSUE TITLE
send bug reports to lbry help email box

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-app#759] opened 2017-11-17 22:49 UTC
## The Issue
https://github.com/lbryio/lbry-app/blob/master/ui/js/page/report.js#L17

We'd like for the bug reports to end up at the help@lbry.io mailbox. The current process uses the [report bug](https://lbryio.github.io/lbry/#report_bug) api call.
Per Jeremy:
"It looks like the app is still using the legacy `report_bug` API command (which ought to be removed entirely)"

My guess is it would need to utilize the API server to send the email, but I could be wrong. We may need an adjacent issue filed under internal-apis.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment] 2017-11-20 22:59
It can presumably use https://developer.helpscout.com/help-desk-api/

**Comment by kauffj** [comment] 2018-03-12 17:06
duplicate of #1078 (keeping that one for description purposes)

**Closed by kauffj** 2018-03-12 17:06 UTC
Labels: needs: exploration, type: improvement
