### ISSUE TITLE
shutdown on startup, with message "The daemon has unexpectedly shutdown. Goodbye."

### ISSUE THREAD

**Issue by TrompoMax** [lbryio/lbry-app#291] opened 2017-06-26 18:53 UTC
### Steps to reproduce
1.Open LBRY app on mac os 10.12.5
2.LBRY app shuts down on its own, with error message "The daemon has unexpectedly shutdown. Goodbye."
3.

### Expected behaviour
Tell us what should happen
I think the App should open, and allow me access to its goodness.

### Actual behaviour
Tell us what happens instead
The app shuts down, and denies me all the goodness.

## System Configuration

 

I cant access that.  App closes on startup.

- LBRY Daemon version:v0.13
- LBRY App version:v0.12.2
- LBRY Installation ID:
- Operating system:Mac OS 10.12.5

**Comment by kauffj** [comment] 2017-06-26 19:19
@TrompoMax thanks for reporting this! However, we cannot debug without more details.

Can you send your `lbrynet.log` file to help@lbry.io and reference this ticket (lbry-app #291)?

**Comment by TrompoMax** [comment] 2017-06-26 19:35
Where would I find lbrynet.log?

**Comment by kauffj** [comment] 2017-06-26 19:35
Oops, meant to include this link: [https://lbry.io/faq/lbry-directories](https://lbry.io/faq/lbry-directories).

**Comment by TrompoMax** [comment] 2017-06-26 20:00
I do not have a LBRY folder in my applications support folder sub directory of Library.  This may be part of the problem.

I ran the software from Terminal, and this is the readout.  Does this help at all?

max-cranleys-macbook:~ workingaccount$ /Applications/LBRY.app/Contents/MacOS/LBRY ; exit;
Checking for lbrynet daemon
lbrynet daemon needs to be launched
Launching daemon: /Applications/LBRY.app/Contents/Resources/app/dist/lbrynet-daemon
2017-06-26 12:55:43,901 INFO     lbrynet.lbrynet_daemon.DaemonControl:92: Starting lbrynet-daemon from command line
2017-06-26 12:55:44,220 INFO     lbrynet.lbrynet_daemon.DaemonServer:64: Using non-authenticated API
2017-06-26 12:55:44,222 INFO     lbrynet.lbrynet_daemon.Daemon:254: Starting lbrynet-daemon
2017-06-26 12:55:44,309 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:174: Starting exchange rate manager
2017-06-26 12:55:44,480 INFO     lbrynet.lbrynet_daemon.Daemon:281: Platform: {"lbrynet_version": "0.13.1rc1", "platform": "Darwin-16.6.0-x86_64-i386-64bit", "os_system": "Darwin", "python_version": "2.7.13", "os_release": "16.6.0", "lbryum_version": "2.8.2", "ip": "2601:644:0:9285:1d0:6c38:e129:1d32", "lbryschema_version": "0.0.7", "processor": "i386", "build": "rc"}
2017-06-26 12:55:44,485 INFO     lbrynet.lbrynet_daemon.Daemon:488: Loading databases
2017-06-26 12:55:44,489 INFO     lbrynet.lbrynet_daemon.Daemon:516: Upgrading your databases
2017-06-26 12:55:44,489 INFO     lbrynet.db_migrator.migrate1to2:9: Doing the migration
2017-06-26 12:55:44,492 ERROR    lbrynet.lbrynet_daemon.DaemonControl:128: Failed to startup
Traceback (most recent call last):
  File "site-packages/lbrynet/lbrynet_daemon/DaemonControl.py", line 125, in start_server_and_listen
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/DaemonServer.py", line 49, in start
  File "site-packages/twisted/internet/defer.py", line 1297, in _inlineCallbacks
  File "site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
  File "site-packages/lbrynet/lbrynet_daemon/Daemon.py", line 262, in setup
  File "site-packages/twisted/python/threadpool.py", line 246, in inContext
  File "site-packages/twisted/python/threadpool.py", line 262, in <lambda>
  File "site-packages/twisted/python/context.py", line 118, in callWithContext
  File "site-packages/twisted/python/context.py", line 81, in callWithContext
  File "site-packages/lbrynet/db_migrator/dbmigrator.py", line 9, in migrate_db
  File "site-packages/lbrynet/db_migrator/migrate1to2.py", line 10, in do_migration
  File "site-packages/lbrynet/db_migrator/migrate1to2.py", line 37, in migrate_blockchainname_db
OperationalError: no such table: claim_ids
2017-06-26 12:55:44,492 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
2017-06-26 12:55:44,493 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_db
2017-06-26 12:55:44,494 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
2017-06-26 12:55:44,495 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_db
The daemon has exited.
Did not request daemon stop, so quitting in 5 seconds.
Quitting.
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by kauffj** [comment] 2017-06-26 20:09
Thanks, the issue is clear from that log so no need to email.

**Comment by TrompoMax** [comment] 2017-06-26 20:29
My pleasure.  Thank you!

**Comment by tzarebczan** [comment] 2017-06-26 21:24
@TrompoMax, another user had a similar issue on MAC and this was suggested: 
Fix: to manually bypass this, delete blockchainname.db and db_revision in the lbrynet data folder.

Looks like you had an older installation, so this directory may be different. Can you search your pc for those files? Maybe then you will find the directory.

We will be working on a guide on how to do a fresh install while preserving most of your data (wallet especially!)

**Comment by TrompoMax** [comment] 2017-06-26 21:37
I did have an older version of the app installed, yes.  Please do let me know when that guide is complete.  I can't find those files, unfortunately.

**Comment by iretrala** [comment] 2017-06-27 05:34
@TrompoMax I can confirm that what @tzarebczan works as I was having the issue, too. Click "Go" in Finder at the top of the screen, use this location exactly: `<~/Library/Application Support/LBRY>`, and voila! You should be able to see those two files mentioned and delete them. All you do then is reopen LBRY.app and you should be good. :)

**Comment by TrompoMax** [comment] 2017-06-27 05:44
Yep, that did it.  Thanks guys!

**Comment by tzarebczan** [comment] 2017-06-27 20:49
Great! We will still work on a guide on how to clean install and then possibly copy over pertinent files.

**Comment by tzarebczan** [comment] 2017-06-27 20:50
@iretrala thanks for the tip, that was going to be part of the documentation (or how to show hidden files).  If you are on Slack, PM me and I'll throw you a couple LBC (my handle is jiggytom).

**Comment by TrompoMax** [comment] 2017-06-27 20:54
Ya, thanks again.  Just for clarity, there are at least 2 Library folders in MacOS.  One for each user, and one for the system.  All of my apps, including LBRY are in my main system applications directory, so I assumed the library folder you were asking me to look into was in that one.  The files I was looking for were actually in my user Library folder.

**Comment by kauffj** [comment] 2017-06-27 21:34
I'm going to close this, since this isn't an issue with the app itself (it's the daemon), the daemon devs know, and a help article is in the pipeline. Thanks all!

**Closed by kauffj** 2017-06-27 21:34 UTC

**Comment by fap-** [comment] 2017-07-09 12:38
For anyone experiencing this issue on linux: the files where located in ~/.lbrynet and removing them fixed the issue.

**Comment by SANOEK60** [comment] 2017-09-20 11:11
I have tried everything without succes please Help !
Do I lost my wallet now?

**Comment by tzarebczan** [comment] 2017-09-20 12:02
Have you looked at https://lbry.io/faq/startup-troubleshooting ?

What os? Please provide logs.

**Comment by SANOEK60** [comment] 2017-09-20 12:58
Already tried everything No results ? IOS Mac pro

**Comment by tzarebczan** [comment] 2017-09-20 13:00
I replied to you on slack, give a reboot, Uninstall, reinstall a try. Then follow my other instructions about the log file.

**Comment by SANOEK60** [comment] 2017-09-20 13:04
I have Deleted all files from previous instalation do not find backup files ...

**Comment by SANOEK60** [comment] 2017-09-20 13:31
If I install on a Windows pc and sign in with my email and give the details from the transfer Bitrex to wallet with address Is it possible to get the coins back?

**Comment by SANOEK60** [comment] 2017-09-20 14:20
I have new install now on a Windows pc !
How to get my coins in the wallet ?

**Comment by tzarebczan** [comment] 2017-09-20 14:40
@SANOEK60 I'll work with you on Slack. Check your messages.

**Comment by lxcosmo** [comment] 2017-10-06 07:07
I have the same problem too! "The daemon has unexpectedly shutdown. Goodbye."
Windows 7 
LBRY_0.16.1 or LBRY_0.15.0 the same
