### ISSUE TITLE
Unexected daemon shudtown

### ISSUE THREAD

**Issue by TTLPUA** [lbryio/lbry-app#376] opened 2017-07-22 09:54 UTC
## The Issue
Unexpected application termination
### Steps to reproduce
1. Run  LBRY_0.13.0.exe install

### Expected behaviour
Application works.

### Actual behaviour
Aplication crash.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:  LBRY_0.13.0
- LBRY Installation ID:
- Operating system:Windows 7, Windows 10 / x64

## Anything Else
lbrynet.log

> 2017-07-22 10:13:57,213 INFO     lbrynet.lbrynet_daemon.DaemonControl:92: Starting lbrynet-daemon from command line
> 2017-07-22 10:14:00,430 INFO     lbrynet.lbrynet_daemon.DaemonServer:64: Using non-authenticated API
> 2017-07-22 10:14:00,430 INFO     lbrynet.lbrynet_daemon.Daemon:254: Starting lbrynet-daemon
> 2017-07-22 10:14:00,651 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:174: Starting exchange rate manager
> 2017-07-22 10:14:02,214 INFO     lbrynet.lbrynet_daemon.Daemon:281: Platform: {"lbrynet_version": "0.13.1", "platform": "Windows-7-6.1.7601-SP1", "os_system": "Windows", "python_version": "2.7.13", "os_release": "7", "lbryum_version": "2.8.4", "ip": "95.133.157.3", "lbryschema_version": "0.0.7", "processor": "AMD64 Family 18 Model 1 Stepping 0, AuthenticAMD", "build": "release"}
> 2017-07-22 10:14:02,246 INFO     lbrynet.lbrynet_daemon.Daemon:488: Loading databases
> 2017-07-22 10:14:02,246 ERROR    lbrynet.lbrynet_daemon.DaemonControl:128: Failed to startup
> Traceback (most recent call last):
>   File "site-packages\lbrynet\lbrynet_daemon\DaemonControl.py", line 125, in start_server_and_listen
>   File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
>   File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
>   File "site-packages\lbrynet\lbrynet_daemon\DaemonServer.py", line 49, in start
>   File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
>   File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
>   File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 261, in setup
>   File "site-packages\twisted\python\threadpool.py", line 246, in inContext
>   File "site-packages\twisted\python\threadpool.py", line 262, in <lambda>
>   File "site-packages\twisted\python\context.py", line 118, in callWithContext
>   File "site-packages\twisted\python\context.py", line 81, in callWithContext
>   File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 497, in _setup_data_directory
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)
> 2017-07-22 10:14:02,262 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
> 2017-07-22 10:14:02,263 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_db
> 2017-07-22 10:14:02,266 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
> 2017-07-22 10:14:02,266 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_db
> 2017-07-22 12:45:53,214 INFO     lbrynet.lbrynet_daemon.DaemonControl:92: Starting lbrynet-daemon from command line
> 2017-07-22 12:45:55,782 INFO     lbrynet.lbrynet_daemon.DaemonServer:64: Using non-authenticated API
> 2017-07-22 12:45:55,789 INFO     lbrynet.lbrynet_daemon.Daemon:254: Starting lbrynet-daemon
> 2017-07-22 12:45:55,984 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:174: Starting exchange rate manager
> 2017-07-22 12:45:57,221 INFO     lbrynet.lbrynet_daemon.Daemon:281: Platform: {"lbrynet_version": "0.13.1", "platform": "Windows-7-6.1.7601-SP1", "os_system": "Windows", "python_version": "2.7.13", "os_release": "7", "lbryum_version": "2.8.4", "ip": "95.133.157.3", "lbryschema_version": "0.0.7", "processor": "AMD64 Family 18 Model 1 Stepping 0, AuthenticAMD", "build": "release"}
> 2017-07-22 12:45:57,227 INFO     lbrynet.lbrynet_daemon.Daemon:488: Loading databases
> 2017-07-22 12:45:57,233 WARNING  lbrynet.lbrynet_daemon.Daemon:499: db_revision file not found. Creating it
> 2017-07-22 12:45:57,250 INFO     lbrynet.lbrynet_daemon.Daemon:516: Upgrading your databases
> 2017-07-22 12:45:57,253 INFO     lbrynet.db_migrator.migrate1to2:9: Doing the migration
> 2017-07-22 12:45:57,253 INFO     lbrynet.db_migrator.migrate1to2:11: Migration succeeded
> 2017-07-22 12:45:57,255 INFO     lbrynet.db_migrator.migrate2to3:9: Doing the migration
> 2017-07-22 12:45:57,256 INFO     lbrynet.db_migrator.migrate2to3:11: Migration succeeded
> 2017-07-22 12:45:57,256 INFO     lbrynet.lbrynet_daemon.Daemon:512: Finished upgrading the databases.
> 2017-07-22 12:45:57,257 INFO     lbrynet.lbrynet_daemon.Daemon:558: Using lbryum wallet
> 2017-07-22 12:45:58,967 INFO     lbrynet.core.Session:213: Set UPnP redirect for TCP port 3333
> 2017-07-22 12:45:59,454 INFO     lbrynet.core.Session:224: Set UPnP redirect for UDP port 4444
> 2017-07-22 12:45:59,456 INFO     lbrynet.core.Session:254: Starting DHT
> 2017-07-22 12:45:59,618 INFO     lbrynet.dht.protocol:216: DHT listening on UDP 4444
> 2017-07-22 12:45:59,624 INFO     lbrynet.core.RateLimiter:72: Starting <lbrynet.core.RateLimiter.RateLimiter object at 0x04504FB0>
> 2017-07-22 12:45:59,625 ERROR    lbrynet.lbrynet_daemon.DaemonControl:128: Failed to startup
> Traceback (most recent call last):
>   File "site-packages\lbrynet\lbrynet_daemon\DaemonControl.py", line 125, in start_server_and_listen
>   File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
>   File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
>   File "site-packages\lbrynet\lbrynet_daemon\DaemonServer.py", line 49, in start
>   File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
>   File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
>   File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 264, in setup
>   File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
>   File "site-packages\lbrynet\core\Session.py", line 167, in <lambda>
>   File "site-packages\lbrynet\core\Session.py", line 314, in _setup_other_components
>   File "site-packages\lbrynet\core\BlobManager.py", line 96, in setup
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 9-14: ordinal not in range(128)
> 2017-07-22 12:45:59,628 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
> 2017-07-22 12:45:59,628 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_wallet
> 2017-07-22 12:45:59,631 INFO     lbrynet.core.Session:172: Shutting down <lbrynet.core.Session.Session object at 0x04504E10>
> 2017-07-22 12:45:59,632 INFO     lbrynet.core.BlobAvailability:35: Stopping <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x0451B230>
> 2017-07-22 12:45:59,634 INFO     lbrynet.core.RateLimiter:83: Stopping <lbrynet.core.RateLimiter.RateLimiter object at 0x04504FB0>
> 2017-07-22 12:45:59,634 INFO     lbrynet.core.client.DHTPeerFinder:28: Stopping <lbrynet.core.client.DHTPeerFinder.DHTPeerFinder object at 0x0451B8B0>
> 2017-07-22 12:45:59,634 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping <lbrynet.core.server.DHTHashAnnouncer.DHTHashAnnouncer object at 0x044F5570>
> 2017-07-22 12:45:59,635 INFO     lbrynet.core.Wallet:437: Stopping <lbrynet.core.Wallet.LBRYumWallet object at 0x045046D0>
> 2017-07-22 12:45:59,638 ERROR    lbrynet.core.Wallet:503: Something went wrong during manage. Error message: 'NoneType' object has no attribute 'get_balance'
> 2017-07-22 12:45:59,641 ERROR    lbrynet.core.Wallet:434: An error occurred stopping the wallet: Traceback (most recent call last):
>   File "site-packages\twisted\internet\defer.py", line 308, in addCallbacks
>     
>   File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 490, in <lambda>
>     
>   File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
>     
> --- <exception caught here> ---
>   File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 520, in update_balance
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 1276, in _update_balance
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 1261, in _run_cmd_as_defer_succeed
>     
>   File "site-packages\lbryum\commands.py", line 153, in func_wrapper
>     
>   File "site-packages\lbryum\commands.py", line 363, in getbalance
>     
> exceptions.AttributeError: 'NoneType' object has no attribute 'get_balance'
> 
> 2017-07-22 12:45:59,644 INFO     lbrynet.core.BlobManager:103: Stopping the DiskBlobManager
> 2017-07-22 12:45:59,648 INFO     lbrynet.core.Session:322: Unsetting upnp for <lbrynet.core.Session.Session object at 0x04504E10>
> 2017-07-22 12:45:59,651 INFO     lbrynet.dht.protocol:464: Stopping DHT
> 2017-07-22 12:45:59,651 INFO     lbrynet.dht.protocol:480: DHT stopped
> 2017-07-22 12:46:01,092 INFO     lbrynet.core.Session:336: Removed UPnP redirect for TCP 3333.
> 2017-07-22 12:46:01,525 INFO     lbrynet.core.Session:336: Removed UPnP redirect for UDP 4444.
> 2017-07-22 12:46:01,526 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
> 2017-07-22 12:46:01,528 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_wallet
> 2017-07-22 12:46:01,529 INFO     lbrynet.core.Session:172: Shutting down <lbrynet.core.Session.Session object at 0x04504E10>
> 2017-07-22 12:46:01,529 INFO     lbrynet.core.BlobAvailability:35: Stopping <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x0451B230>
> 2017-07-22 12:46:01,532 INFO     lbrynet.core.RateLimiter:83: Stopping <lbrynet.core.RateLimiter.RateLimiter object at 0x04504FB0>
> 2017-07-22 12:46:01,532 INFO     lbrynet.core.client.DHTPeerFinder:28: Stopping <lbrynet.core.client.DHTPeerFinder.DHTPeerFinder object at 0x0451B8B0>
> 2017-07-22 12:46:01,532 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping <lbrynet.core.server.DHTHashAnnouncer.DHTHashAnnouncer object at 0x044F5570>
> 2017-07-22 12:46:01,532 INFO     lbrynet.core.Wallet:437: Stopping <lbrynet.core.Wallet.LBRYumWallet object at 0x045046D0>
> 2017-07-22 12:46:01,533 ERROR    lbrynet.core.Wallet:503: Something went wrong during manage. Error message: 'NoneType' object has no attribute 'get_balance'
> 2017-07-22 12:46:01,538 ERROR    lbrynet.core.Wallet:434: An error occurred stopping the wallet: Traceback (most recent call last):
>   File "site-packages\twisted\internet\defer.py", line 308, in addCallbacks
>     
>   File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 490, in <lambda>
>     
>   File "site-packages\twisted\internet\defer.py", line 1445, in unwindGenerator
>     
> --- <exception caught here> ---
>   File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 520, in update_balance
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 1276, in _update_balance
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 1261, in _run_cmd_as_defer_succeed
>     
>   File "site-packages\lbryum\commands.py", line 153, in func_wrapper
>     
>   File "site-packages\lbryum\commands.py", line 363, in getbalance
>     
> exceptions.AttributeError: 'NoneType' object has no attribute 'get_balance'
> 
> 2017-07-22 12:46:01,540 INFO     lbrynet.core.BlobManager:103: Stopping the DiskBlobManager
> 2017-07-22 12:46:01,542 INFO     lbrynet.core.Session:322: Unsetting upnp for <lbrynet.core.Session.Session object at 0x04504E10>
> 2017-07-22 12:46:02,565 CRITICAL twisted:154: Unhandled error in Deferred:
> 2017-07-22 12:46:02,565 CRITICAL twisted:154: 
> Traceback (most recent call last):
>   File "site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
>   File "site-packages\lbrynet\core\BlobManager.py", line 107, in stop
>   File "site-packages\twisted\enterprise\adbapi.py", line 397, in close
>   File "site-packages\twisted\enterprise\adbapi.py", line 405, in finalClose
>   File "site-packages\twisted\python\threadpool.py", line 274, in stop
>   File "site-packages\twisted\_threads\_team.py", line 226, in quit
>   File "site-packages\twisted\_threads\_convenience.py", line 35, in set
>   File "site-packages\twisted\_threads\_convenience.py", line 46, in check
> AlreadyQuit

## Screenshots

<a href="https://ibb.co/j35Lek"><img src="https://preview.ibb.co/mbgtzk/1.png" alt="1" border="0"></a>
<a href="https://ibb.co/eXFLek"><img src="https://preview.ibb.co/g5rtzk/2.png" alt="2" border="0"></a>
<a href="https://ibb.co/grxYzk"><img src="https://preview.ibb.co/eBe2s5/3.png" alt="3" border="0"></a>

**Comment by tzarebczan** [comment] 2017-07-22 17:03
Duplicate of https://github.com/lbryio/lbry/issues/794 most likely 

Can you tell me your userpath in c:/users/...

**Comment by TTLPUA** [comment] 2017-07-23 07:04
2-d PC/  Win 10, x64, C:\Users\GreyWolf\AppData\Roaming\lbrynet\

> 2017-07-23 09:57:11,197 INFO     lbrynet.lbrynet_daemon.DaemonControl:92: Starting lbrynet-daemon from command line
> 2017-07-23 09:57:13,464 INFO     lbrynet.lbrynet_daemon.DaemonServer:64: Using non-authenticated API
> 2017-07-23 09:57:13,470 INFO     lbrynet.lbrynet_daemon.Daemon:254: Starting lbrynet-daemon
> 2017-07-23 09:57:13,651 INFO     lbrynet.lbrynet_daemon.ExchangeRateManager:174: Starting exchange rate manager
> 2017-07-23 09:57:14,372 INFO     lbrynet.lbrynet_daemon.Daemon:281: Platform: {"lbrynet_version": "0.13.1", "platform": "Windows-10-10.0.14393", "os_system": "Windows", "python_version": "2.7.13", "os_release": "10", "lbryum_version": "2.8.4", "ip": "Could not determine IP", "lbryschema_version": "0.0.7", "processor": "AMD64 Family 21 Model 16 Stepping 1, AuthenticAMD", "build": "release"}
> 2017-07-23 09:57:14,378 INFO     lbrynet.lbrynet_daemon.Daemon:488: Loading databases
> 2017-07-23 09:57:14,401 WARNING  lbrynet.lbrynet_daemon.Daemon:499: db_revision file not found. Creating it
> 2017-07-23 09:57:14,404 INFO     lbrynet.lbrynet_daemon.Daemon:516: Upgrading your databases
> 2017-07-23 09:57:14,405 INFO     lbrynet.db_migrator.migrate1to2:9: Doing the migration
> 2017-07-23 09:57:14,407 INFO     lbrynet.db_migrator.migrate1to2:11: Migration succeeded
> 2017-07-23 09:57:14,407 INFO     lbrynet.db_migrator.migrate2to3:9: Doing the migration
> 2017-07-23 09:57:14,407 INFO     lbrynet.db_migrator.migrate2to3:11: Migration succeeded
> 2017-07-23 09:57:14,408 INFO     lbrynet.lbrynet_daemon.Daemon:512: Finished upgrading the databases.
> 2017-07-23 09:57:14,411 INFO     lbrynet.lbrynet_daemon.Daemon:558: Using lbryum wallet
> 2017-07-23 09:57:15,611 INFO     lbrynet.core.Session:213: Set UPnP redirect for TCP port 3333
> 2017-07-23 09:57:15,799 INFO     lbrynet.core.Session:224: Set UPnP redirect for UDP port 4444
> 2017-07-23 09:57:15,799 INFO     lbrynet.core.Session:254: Starting DHT
> 2017-07-23 09:57:15,858 INFO     lbrynet.dht.protocol:216: DHT listening on UDP 4444
> 2017-07-23 09:57:15,861 INFO     lbrynet.core.RateLimiter:72: Starting <lbrynet.core.RateLimiter.RateLimiter object at 0x045E5770>
> 2017-07-23 09:57:15,861 INFO     lbrynet.core.BlobManager:97: Setting up the DiskBlobManager. blob_dir: C:\Users\GreyWolf\AppData\Roaming\lbrynet\blobfiles, db_file: C:\Users\GreyWolf\AppData\Roaming\lbrynet\blobs.db
> 2017-07-23 09:57:16,801 INFO     lbrynet.core.Wallet:1143: Loading the wallet
> 2017-07-23 09:57:23,430 INFO     lbrynet.core.Wallet:1149: Running the wallet for the first time. This may take a moment.
> 2017-07-23 09:57:43,046 INFO     lbrynet.core.Wallet:1234: Local Height: 211436, remote height: 211439, behind: 3
> 2017-07-23 09:57:43,813 INFO     lbrynet.core.Wallet:1234: Local Height: 211436, remote height: 211439, behind: 1
> 2017-07-23 09:57:44,009 INFO     lbrynet.core.Wallet:1234: Local Height: 211439, remote height: 211439, behind: 0
> 2017-07-23 09:57:44,009 INFO     lbrynet.core.Wallet:1242: Wallet Loaded
> 2017-07-23 09:57:44,009 INFO     lbrynet.core.Wallet:1167: Subscribing to addresses
> 2017-07-23 09:57:44,109 INFO     lbrynet.core.Wallet:1169: Synchronized wallet
> 2017-07-23 09:57:44,111 INFO     lbrynet.core.BlobAvailability:30: Starting <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x045E5570>
> 2017-07-23 09:57:44,121 INFO     lbrynet.lbrynet_daemon.Daemon:531: Starting to setup up file manager
> 2017-07-23 09:57:44,384 INFO     lbrynet.lbryfilemanager.EncryptedFileManager:126: Started 0 lbry files
> 2017-07-23 09:57:44,385 INFO     lbrynet.lbrynet_daemon.Daemon:542: Done setting up file manager
> 2017-07-23 09:57:44,388 ERROR    lbrynet.lbrynet_daemon.Daemon:330: Couldn't bind to port 3333. Traceback (most recent call last):
>   File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 327, in _start_server
>   File "site-packages\twisted\internet\posixbase.py", line 478, in listenTCP
>   File "site-packages\twisted\internet\tcp.py", line 983, in startListening
> CannotListenError: Couldn't listen on any:3333: [Errno 10048] Обычно разрешается только одно использование адреса сокета (протокол/сетевой адрес/порт).
> 
> 2017-07-23 09:57:44,390 ERROR    lbrynet.lbrynet_daemon.DaemonControl:128: Failed to startup
> Traceback (most recent call last):
>   File "site-packages\lbrynet\lbrynet_daemon\DaemonControl.py", line 125, in start_server_and_listen
>   File "site-packages\twisted\internet\defer.py", line 1297, in _inlineCallbacks
>   File "site-packages\twisted\python\failure.py", line 389, in throwExceptionIntoGenerator
>   File "site-packages\lbrynet\lbrynet_daemon\DaemonServer.py", line 49, in start
>   File "site-packages\twisted\internet\defer.py", line 1299, in _inlineCallbacks
>   File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 270, in setup
>   File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 381, in _setup_server
>   File "site-packages\lbrynet\lbrynet_daemon\Daemon.py", line 331, in _start_server
> ValueError: ('%s lbrynet may already be running on your computer.', "Couldn't listen on any:3333: [Errno 10048] \xce\xe1\xfb\xf7\xed\xee \xf0\xe0\xe7\xf0\xe5\xf8\xe0\xe5\xf2\xf1\xff \xf2\xee\xeb\xfc\xea\xee \xee\xe4\xed\xee \xe8\xf1\xef\xee\xeb\xfc\xe7\xee\xe2\xe0\xed\xe8\xe5 \xe0\xe4\xf0\xe5\xf1\xe0 \xf1\xee\xea\xe5\xf2\xe0 (\xef\xf0\xee\xf2\xee\xea\xee\xeb/\xf1\xe5\xf2\xe5\xe2\xee\xe9 \xe0\xe4\xf0\xe5\xf1/\xef\xee\xf0\xf2).")
> 2017-07-23 09:57:44,391 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
> 2017-07-23 09:57:44,392 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_server
> 2017-07-23 09:57:44,392 INFO     lbrynet.lbryfilemanager.EncryptedFileManager:181: Stopping 0 lbry files
> 2017-07-23 09:57:44,401 INFO     lbrynet.lbryfilemanager.EncryptedFileManager:259: Stopped <lbrynet.lbryfilemanager.EncryptedFileManager.EncryptedFileManager object at 0x047CA9B0>
> 2017-07-23 09:57:44,401 INFO     lbrynet.core.Session:172: Shutting down <lbrynet.core.Session.Session object at 0x045E5FD0>
> 2017-07-23 09:57:44,401 INFO     lbrynet.core.BlobAvailability:35: Stopping <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x045E5570>
> 2017-07-23 09:57:44,403 INFO     lbrynet.core.RateLimiter:83: Stopping <lbrynet.core.RateLimiter.RateLimiter object at 0x045E5770>
> 2017-07-23 09:57:44,403 INFO     lbrynet.core.client.DHTPeerFinder:28: Stopping <lbrynet.core.client.DHTPeerFinder.DHTPeerFinder object at 0x045D9910>
> 2017-07-23 09:57:44,404 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping <lbrynet.core.server.DHTHashAnnouncer.DHTHashAnnouncer object at 0x045D9930>
> 2017-07-23 09:57:44,404 INFO     lbrynet.core.Wallet:437: Stopping <lbrynet.core.Wallet.LBRYumWallet object at 0x0453C250>
> 2017-07-23 09:57:44,428 INFO     lbrynet.core.Wallet:1194: Stopped wallet
> 2017-07-23 09:57:44,428 INFO     lbrynet.core.Wallet:1197: Stopped connection to lbryum server
> 2017-07-23 09:57:44,430 INFO     lbrynet.core.BlobManager:103: Stopping the DiskBlobManager
> 2017-07-23 09:57:44,430 INFO     lbrynet.core.Session:322: Unsetting upnp for <lbrynet.core.Session.Session object at 0x045E5FD0>
> 2017-07-23 09:57:44,431 INFO     lbrynet.dht.protocol:464: Stopping DHT
> 2017-07-23 09:57:44,431 INFO     lbrynet.dht.protocol:480: DHT stopped
> 2017-07-23 09:57:45,602 INFO     lbrynet.core.Session:336: Removed UPnP redirect for TCP 3333.
> 2017-07-23 09:57:45,730 INFO     lbrynet.core.Session:336: Removed UPnP redirect for UDP 4444.
> 2017-07-23 09:57:45,733 INFO     lbrynet.lbrynet_daemon.Daemon:412: Closing lbrynet session
> 2017-07-23 09:57:45,733 INFO     lbrynet.lbrynet_daemon.Daemon:413: Status at time of shutdown: loading_server
> 2017-07-23 09:57:45,733 INFO     lbrynet.lbryfilemanager.EncryptedFileManager:181: Stopping 0 lbry files
> 2017-07-23 09:57:45,734 INFO     lbrynet.lbryfilemanager.EncryptedFileManager:259: Stopped <lbrynet.lbryfilemanager.EncryptedFileManager.EncryptedFileManager object at 0x047CA9B0>
> 2017-07-23 09:57:45,734 INFO     lbrynet.core.Session:172: Shutting down <lbrynet.core.Session.Session object at 0x045E5FD0>
> 2017-07-23 09:57:45,736 INFO     lbrynet.core.BlobAvailability:35: Stopping <lbrynet.core.BlobAvailability.BlobAvailabilityTracker object at 0x045E5570>
> 2017-07-23 09:57:45,736 INFO     lbrynet.core.RateLimiter:83: Stopping <lbrynet.core.RateLimiter.RateLimiter object at 0x045E5770>
> 2017-07-23 09:57:45,736 INFO     lbrynet.core.client.DHTPeerFinder:28: Stopping <lbrynet.core.client.DHTPeerFinder.DHTPeerFinder object at 0x045D9910>
> 2017-07-23 09:57:45,736 INFO     lbrynet.core.server.DHTHashAnnouncer:31: Stopping <lbrynet.core.server.DHTHashAnnouncer.DHTHashAnnouncer object at 0x045D9930>
> 2017-07-23 09:57:45,737 INFO     lbrynet.core.Wallet:437: Stopping <lbrynet.core.Wallet.LBRYumWallet object at 0x0453C250>
> 2017-07-23 09:57:45,740 ERROR    lbrynet.core.Wallet:434: An error occurred stopping the wallet: Traceback (most recent call last):
>   File "site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 447, in stop
>     
>   File "site-packages\twisted\internet\defer.py", line 319, in addCallback
>     
>   File "site-packages\twisted\internet\defer.py", line 308, in addCallbacks
>     
> --- <exception caught here> ---
>   File "site-packages\twisted\internet\defer.py", line 651, in _runCallbacks
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 447, in <lambda>
>     
>   File "site-packages\lbrynet\core\Wallet.py", line 1193, in _stop
>     
>   File "site-packages\lbryum\wallet.py", line 1306, in stop_threads
>     
>   File "site-packages\lbryum\util.py", line 114, in remove_jobs
>     
> exceptions.ValueError: list.remove(x): x not in list
> 
> 2017-07-23 09:57:45,742 INFO     lbrynet.core.BlobManager:103: Stopping the DiskBlobManager
> 2017-07-23 09:57:45,744 INFO     lbrynet.core.Session:322: Unsetting upnp for <lbrynet.core.Session.Session object at 0x045E5FD0>
> 2017-07-23 09:57:46,769 CRITICAL twisted:154: Unhandled error in Deferred:
> 2017-07-23 09:57:46,770 CRITICAL twisted:154: 
> Traceback (most recent call last):
>   File "site-packages\twisted\internet\defer.py", line 150, in maybeDeferred
>   File "site-packages\lbrynet\core\BlobManager.py", line 107, in stop
>   File "site-packages\twisted\enterprise\adbapi.py", line 397, in close
>   File "site-packages\twisted\enterprise\adbapi.py", line 405, in finalClose
>   File "site-packages\twisted\python\threadpool.py", line 274, in stop
>   File "site-packages\twisted\_threads\_team.py", line 226, in quit
>   File "site-packages\twisted\_threads\_convenience.py", line 35, in set
>   File "site-packages\twisted\_threads\_convenience.py", line 46, in check
> AlreadyQuit

**Comment by ptc4cash** [comment] 2017-07-24 03:03
I am having the same issue,

After having ti running for days i needed a reset and now my coins are stuck in the wallet but daemon is not running correctly,

What has happened??

Please help as this turns into major loss if we can not get to our coins and turns a lot of us away from mining,

Thanks

**Comment by tzarebczan** [comment] 2017-07-24 03:10
@ptc4cash you are having a different issue... "Couldn't listen on any:3333: [Errno 10048]". Are you running mining softwasre? It may run on that port. Run lbry first, turn the Mining software. We are looking into user configurable ports.

**Comment by ptc4cash** [comment] 2017-07-24 03:11
Hey mate thanks for quick reply,

No that was a issue i had earlier yes, i am not mining it on the pc i am running wallet from :(

**Comment by TTLPUA** [comment] 2017-07-24 05:03
@tzarebczan 
thanks, solved

**Closed** 2017-07-24 14:43 UTC

**Comment by tzarebczan** [comment] 2017-07-24 16:41
@ptc4cash - please send your log file to help@lbry.io - https://lbry.io/faq/how-to-find-lbry-log-file
