### ISSUE TITLE
Video fail to start playing

### ISSUE THREAD

**Issue by polminer** [lbryio/lbry-app#200] opened 2017-06-05 21:48 UTC
## The Issue
Video fail to start playing at first download

### Steps to reproduce
1. search lbry://Music#dd0c86a2232273e318dd97bdc43536b9b0273b22
2. Click  on player screen
3.Video start to download
4. Videoplayer Black screen. Can't start, pause, enything.

### Expected behaviour
Video start playing

### Actual behaviour
Black screen - not playing

## System Configuration
About
Your copy of LBRY is up to date.

daemon (lbrynet)	0.10.3
wallet (lbryum)	2.7.22
interface	0.11.9
Platform	Windows (Windows-10-10.0.14393)
Installation ID	5HSNHiJuYxTjjxamfaf32up6aztTVXM3wsW1GTKSsp6c4BY7f9vn1ry1H9Xv7scU39

## Anything Else
 
If Back on Discover   and play again  - video start play.

Another clips playing good. But this lbry://Music#dd0c86a2232273e318dd97bdc43536b9b0273b22 
with problem

## Screenshots

 ![2710](https://cloud.githubusercontent.com/assets/26439658/26804928/66546366-4a52-11e7-9a58-c5b12711c346.png)

![2711](https://cloud.githubusercontent.com/assets/26439658/26804927/66527286-4a52-11e7-8786-d1762ffba986.png)

**Comment by tzarebczan** [comment] 2017-06-07 01:35
Can you please try this on the latest version?

**Comment by polminer** [comment] 2017-06-07 11:34
It looks like a problem in the update for windows
I will wait for correction and then I'll write

https://github.com/lbryio/lbry-app/issues/163#issuecomment-306767285

**Comment by polminer** [comment] 2017-06-07 23:59
Upd:
After update to https://github.com/lbryio/lbry-app/releases/tag/v0.12.0rc6
 to Windows version  i have the same issue.

Can another Windows user testrs confirm this problem?
 Try  lbry://Music#dd0c86a2232273e318dd97bdc43536b9b0273b22
at first download.


Your copy of LBRY is up to date.

daemon (lbrynet)	0.11.0rc1
wallet (lbryum)	2.7.24
interface	0.12.0rc6
Platform	Windows (Windows-10-10.0.14393)
Installation ID	7v4EBdaGmqBZosAGnwF7axqadRDverK6vQ5aLFvtpwDkxa6fiFto8iQ7FRcUSvTznd

**Comment by 6ea86b96** [comment] 2017-06-08 13:15
I can confirm this is an issue. Only on the first attempt to play though. If you find the file in your downloads tab, or navigate to this lbry url when the file is already downloaded then it plays fine.

**Comment by 6ea86b96** [comment] 2017-06-08 14:45
So this seems to be due to the metadata being at the end the file. It also works if you navigate to the page, click on the download link and then click play when download as finished. Perhaps the easiest solution for now would be to catch errors from `render-media` and then attempt to play the file when download has finished.

**Comment by 6ea86b96** [comment] 2017-06-09 09:36
I have a fix for this running locally. The code needs some cleanup. It should be good to go in the next couple of days.

![metadata](https://user-images.githubusercontent.com/20863631/26969936-abe7b202-4d31-11e7-8308-933c2c5e99f4.gif)

**Comment by kauffj** [comment] 2017-06-15 23:37
This is fixed in 0.12.

**Closed by kauffj** 2017-06-15 23:37 UTC
